# Generated by Django 2.2.1 on 2019-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Tipo', models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado')], default='Ativo', max_length=50)),
            ],
        ),
    ]
