# Generated by Django 2.2.1 on 2019-05-29 21:22

from django.db import migrations, models
import vendas.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contato', models.CharField(max_length=200)),
                ('emailcontato', models.EmailField(blank=True, max_length=254)),
                ('emailfinanceiro', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado')], default='Ativo', max_length=50)),
                ('datacadastro', models.DateField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[vendas.models.validate_CNPJ])),
            ],
        ),
    ]
